apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cicd
  annotations:
    harness.io/pipelines: |
      Build: https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/module/ci/orgs/default/projects/automation/pipelines/quickstart/pipeline-studio?storeType=INLINE
    harness.io/services: |
      IDP UI: https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/module/cd/orgs/default/projects/automation/services/nginx
    grafana/dashboard-selector: "http://35.247.91.252/d/RpSjVqWMz/redis-memstore?orgId=1"
spec:
  type: service
  lifecycle: experimental
  owner: guests
  system: examples
  providesApis: [example-grpc-api]
