apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: test-automation
  title: Trigger a simple pipeline
  description: An template for the scaffolder that triggers a simple pipeline
  tags:
    - pipeline
    - harness
spec:
  owner: aashrit.garg@harness.io
  type: service
  steps:
    - id: trigger
      name: Simple Pipeline with wait step
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://qa.harness.io/ng/account/Vp0XSI5MSgiF9p8lIIpThg/module/cd/orgs/default/projects/automation/pipelines/testautomation/executions/tAxCjsL9TFuOuKtUEubr6A/pipeline'   
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
